# key? 32byte (256bit)
jwt:
  secretKey: "123456789012345678901234567890123456789012345678" # 48 characters (48 * 8 = 384 bits)
  refreshKey: "123456789012345678901234567890123456789012345678" # 48 characters (48 * 8 = 384 bits)


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/examplesdb?useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: Yooshin1004!
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: yooshin134@gmail.com
    password: wkyi ubbb aqim rxlt
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    debug: true
